model_type: keyphrase

#data: data/keyphrase/meng17/kp20k
#save_checkpoint_steps: 10000
#keep_checkpoint: 20
seed: 3435
#train_steps: 100000
#valid_steps: 20000
report_every: 100

encoder_type: brnn
rnn_type: GRU
#word_vec_size: 100
#rnn_size: 150
#layers: 1

optim: adam
#learning_rate: 0.002
adagrad_accumulator_init: 0.1
max_grad_norm: 1

#batch_size: 128
#valid_batch_size: 128
#dropout: 0.0
batch_type: sents
normalization: sents

global_attention: mlp
#copy_attn: 'true'
#reuse_copy_attn: 'true'
#bridge: 'true'
tensorboard: 'false'
log_file_level: DEBUG

# new added on April 17, 2019
#context_gate: 'both'
#input_feed: 1
#share_embeddings: 'true'
#position_encoding: 'true'
#copy_loss_by_seqlength: 'false'

#exp: kp20k-one2one-birnn-GRU512-EMB128-ATTNmlp-Dropout00
#save_model: models/keyphrase/meng17/kp20k.one2one.birnn.Dropout00
#log_file: output/keyphrase/meng17/kp20k.one2one.birnn.Dropout00.log
#tensorboard_log_dir: runs/keyphrase/meng17/kp20k.one2one.birnn.Dropout00/

wandb: 'true'
wandb_key: 'c338136c195ab221b8c7cfaa446db16b2e86c6db'

world_size: 1
gpu_ranks:
- 0
#- 1
#master_port: 5000